name: terminator
adopt-info: terminator
summary: A Python-based resource monitor for your terminal. 
description: |
  The goal of this project is to produce a useful tool for arranging terminals. 
  It is inspired by programs such as gnome-multi-term, quadkonsole, etc. in that 
  the main focus is arranging terminals in grids (tabs is the most common default
  method, which Terminator also supports).

  When you run Terminator, you will get a terminal in a window, just like almost every other 
  terminal emulator available. There is also a titlebar which will update as shells/programs
  inside the terminal tell it to. Also on the titlebar is a small button that opens the 
  grouping menu. From here you can put terminals into groups, which allows you to control
  multiple terminals simultaneously.
    
license: GPL-2.0

base: core20
grade: stable
confinement: classic

apps:
  terminator:
    command: usr/local/bin/terminator
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages

parts:
  terminator:
    source: https://github.com/gnome-terminator/terminator
    source-type: git
    plugin: python
    
    build-packages:
      - python3-dev
      - python3-gi 
      - python3-gi-cairo 
      - python3-psutil 
      - python3-configobj 
      - gir1.2-keybinder-3.0 
      - gir1.2-vte-2.91 
      - gettext 
      - intltool 
      - dbus-x11
      - libcext0
      - python3-pip
      
    stage-packages:
      - python3-dev
      - python3-gi 
      - python3-gi-cairo 
      - python3-configobj 
      - gir1.2-keybinder-3.0 
      - gir1.2-vte-2.91 
      - gettext 
      - intltool 
      - dbus-x11
      - libcext0
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
    
    override-build: |
      pip install psutil cairo gi configobj cext
      python3 setup.py build
      python3 setup.py install --prefix=$SNAPCRAFT_PART_INSTALL/usr/local --single-version-externally-managed --record=install-files.txt
